targets:
  ubuntu-14.04:
installer: https://github.com/pkgr/installer.git#master
wizards:
  - https://github.com/pkgr/addon-apache2.git
  - ./packaging/wizards/siptreadmill
after:
  - rm -rf .git app/assets packaging sipp treadmill tmp vendor/cache/*.gem
