#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'treadmill', path: 'treadmill'
cookbook 'sipp', path: 'sipp'

cookbook 'apt'
cookbook 'freeswitch', git: 'https://github.com/mojolingo/freeswitch-cookbook.git'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm.git'
cookbook 'sqlite'
cookbook 'redis', git: 'https://github.com/phlipper/chef-redis.git'
cookbook 'sudo'
cookbook 'postgresql'
cookbook 'database'
cookbook 'locale'
cookbook 'phantomjs', '0.1.0'
